-- 코드를 입력하세요
SELECT CONCAT("/home/grep/src/",ugb.BOARD_ID,"/",FILE_ID,FILE_NAME,FILE_EXT) as FILE_PATH FROM USED_GOODS_BOARD ugb JOIN USED_GOODS_FILE ugf
ON ugb.BOARD_ID = ugf.BOARD_ID 
WHERE VIEWS = (select max(views) from USED_GOODS_BOARD)
ORDER BY FILE_PATH DESC;

